In [66]:
import pandas as pd
data = pd.read_csv(r"C:\Users\amany\Desktop\weight-height.csv")
print(data.head(25))
# print(" ")
# print("It's Female time...")
# print(" ")
# print(data[data['Gender']=='Female'])

   Gender     Height      Weight
0    Male  73.847017  241.893563
1    Male  68.781904  162.310473
2    Male  74.110105  212.740856
3    Male  71.730978  220.042470
4    Male  69.881796  206.349801
5    Male  67.253016  152.212156
6    Male  68.785081  183.927889
7    Male  68.348516  167.971110
8    Male  67.018950  175.929440
9    Male  63.456494  156.399676
10   Male  71.195382  186.604926
11   Male  71.640805  213.741169
12   Male  64.766329  167.127461
13   Male  69.283070  189.446181
14   Male  69.243732  186.434168
15   Male  67.645620  172.186930
16   Male  72.418317  196.028506
17   Male  63.974326  172.883470
18   Male  69.640060  185.983958
19   Male  67.936005  182.426648
20   Male  67.915050  174.115929
21   Male  69.439440  197.731422
22   Male  66.149132  149.173566
23   Male  75.205974  228.761781
24   Male  67.893196  162.006652


In [5]:
#data analyze
data.describe()

Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
Gender    10000 non-null object
Height    10000 non-null float64
Weight    10000 non-null float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


In [6]:
data.isnull()

Gender  Height  Weight
0      False   False   False
1      False   False   False
2      False   False   False
3      False   False   False
4      False   False   False
...      ...     ...     ...
9995   False   False   False
9996   False   False   False
9997   False   False   False
9998   False   False   False
9999   False   False   False

[10000 rows x 3 columns]

In [8]:
data.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [43]:
import numpy as np
data['Gender'].replace('Male',1,inplace=True)
data['Gender'].replace('Female',0,inplace=True)
x=data.iloc[:,:-1].values #calling first two column
y=data.iloc[:,2].values   #calling last column
y

array([241.89356318, 162.31047252, 212.74085556, ..., 128.47531878,
       163.85246135, 113.64910268])

In [51]:
#split dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.2, random_state=0) #80% for training purpose and 20% for test 
y_test

array([138.0857961 , 187.36336585, 216.53319128, ..., 152.42003134,
       170.10064728, 158.20620596])

In [38]:
#Fit regression model
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
#make prediction using test data
lin_pred = lin_reg.predict(X_test)
lin_pred

array([141.93828842, 176.55658781, 219.77836195, ..., 149.97129636,
       166.83374903, 138.87940678])

In [50]:
#model accuracy
from sklearn import metrics
print('R square = ', metrics.r2_score(y_test,lin_pred))
print('Mean squared error = ',metrics.mean_squared_error(y_test,lin_pred))
print('Mean absolute error = ',metrics.mean_absolute_error(y_test,lin_pred))


R square =  0.9052889824534557
Mean squared error =  97.87152220196164
Mean absolute error =  7.955916525326746


In [67]:
#predict weight
weight_pred = lin_reg.predict([[0,69]])
print("My predicted weight = ",weight_pred)

My predicted weight =  [167.435143]
